server:
  port: 80
#  ssl:
#    enabled: true
#    key-alias: scg
#    key-store-password: scg1234
#    key-store: classpath:scg-keystore.p12
#    key-store-type: PKCS12
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # 每隔5秒向注册中心发送心跳
    lease-renewal-interval-in-seconds: 5
    # 连续10秒没有向服务端发送心跳，让注册中心踢掉自己
    lease-expiration-duration-in-seconds: 10
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
spring:
  application:
    name: gateway
  redis:
    host: xinlus.cn
    port: 6379
    password: xinlus
    database: 0
  cloud:
    gateway:
#      httpclient:
#        ssl:
#          useInsecureTrustManager: true
#        ssl:
#          trustedX509Certificates:
#          - cert1.pem
#          - cert2.pem
      routes:
        - id: test-web
#          uri: http://localhost
          uri: lb://test-web
          predicates: 
            - Path=/web/**
          filters:
            - name: SetStatus
              args:
                status: 401
            - StripPrefix=1
      default-filters:
#      限流
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@hostAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 10  
            redis-rate-limiter.burstCapacity: 20
            maxSize: 10485760
            status: 401
            retries: 3
            statues: BAD_GATEWAY     
        - name: Hystrix
          args:
            name: fallback
#            熔断策略
            fallbackUri: forward:/fallback
            